### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by edclement** [xlts-dev/verdaccio-prometheus-middleware#11]
We should License under MIT with Copyright XLTS.dev

**Comment by Splaktar** [comment]
And publish a new version with this license.

**Comment by edclement** [comment]
@Splaktar I'm thinking this issue, #9, and #10 can all get tackled fairly quick and then we publish tag and publish `v1.1.0`. Do you agree?

**Comment by Splaktar** [comment]
@edclement sounds good.
