### ISSUE TITLE
Publish to public npm registry

### ISSUE THREAD

**Issue by edclement** [xlts-dev/verdaccio-prometheus-middleware#6]
We should publish this package to the public npm registry. @Splaktar I was thinking of setting up CI to publish this package on tag creation. I was planning on following [this](https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQiAnuGNBhCPARIsACbnLzr95GGf4uZb5Ygc-9Nqgu0-9r1k92bVPhgUO3i7rjBYEW_m6u48JrsaAsIxEALw_wcB) and [this](https://circleci.com/blog/continuous-package-publishing-part-ii-automated-npm-publishing-with-circleci-and-packagecloud/) article.

Additionally, we could leverage `semantic-release` to automatically increment version numbers using our CI which could then trigger the publish workflow. There is a good article on how to set this up with CircleCI [here](https://medium.com/swlh/how-to-automate-continuous-integration-and-development-versioning-and-publishing-a7d4b3311f3). If we go this route, I'm assuming you would want to stick with the[ default AngularJS commit message inspired format](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format). If we went this route I think it would make sense to tackle #5 first and then leverage [conventional-changelog/commitlint](https://github.com/conventional-changelog/commitlint) to ensure our commit messages follow the standard.

Let me know your thoughts.

**Comment by Splaktar** [comment]
That sounds good to me. I don't have a preference for which conventional-changelog tool we use.

The commit format that we use atm is https://github.com/xlts-dev/angular.js/blob/master/DEVELOPERS.md#commits.

For enforcement, we [currently use](https://github.com/xlts-dev/angular.js/blob/9f6dc5cae6f5fbbcaf1e277bd3473d6f9634c6d2/package.json#L154-L158) `commitizen`, but if that's out of date now, I'm happy to switch tools to something better supported:
```json
  "config": {
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    }
  }
```

**Comment by edclement** [comment]
@Splaktar are you OK with me publishing this to the public npm at this point?

**Comment by Splaktar** [comment]
Yes, it looks like it will be our first publish to npm 🚀

**Comment by edclement** [comment]
Done: https://www.npmjs.com/package/@xlts.dev/verdaccio-prometheus-middleware
